const Map<String, String> enUS = {
  // General
  'app_name': 'Parivartan Sutra',
  'ok': 'OK',
  'cancel': 'Cancel',
  'yes': 'Yes',
  'no': 'No',
  'confirm': 'Confirm',
  'close': 'Close',
  'back': 'Back',
  'next': 'Next',
  'done': 'Done',
  'save': 'Save',
  'edit': 'Edit',
  'delete': 'Delete',
  'retry': 'Retry',
  'loading': 'Loading...',
  'please_wait': 'Please wait...',
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'info': 'Info',
  'search': 'Search',
  'no_data': 'No data found',
  'something_went_wrong': 'Something went wrong',
  'try_again': 'Try again',

  // Auth
  'login': 'Login',
  'logout': 'Logout',
  'register': 'Register',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'sign_out': 'Sign Out',
  'forgot_password': 'Forgot Password?',
  'reset_password': 'Reset Password',
  'change_password': 'Change Password',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'full_name': 'Full Name',
  'phone_number': 'Phone Number',
  'otp': 'OTP',
  'enter_otp': 'Enter OTP',
  'resend_otp': 'Resend OTP',
  'verify': 'Verify',
  'verification': 'Verification',

  // Validation
  'field_required': 'This field is required',
  'invalid_email': 'Please enter a valid email address',
  'invalid_phone': 'Please enter a valid 10-digit phone number',
  'password_too_short': 'Password must be at least 8 characters',
  'password_too_long': 'Password must not exceed 32 characters',
  'password_no_uppercase': 'Password must contain at least one uppercase letter',
  'password_no_lowercase': 'Password must contain at least one lowercase letter',
  'password_no_digit': 'Password must contain at least one digit',
  'password_no_special': 'Password must contain at least one special character',
  'passwords_not_match': 'Passwords do not match',
  'invalid_otp': 'Please enter a valid 6-digit OTP',
  'name_too_short': 'Name must be at least 2 characters',
  'name_too_long': 'Name must not exceed 50 characters',

  // Network
  'no_internet': 'No internet connection',
  'network_error': 'Network error. Please try again.',
  'timeout_error': 'Request timed out. Please try again.',
  'server_error': 'Server error. Please try again later.',
  'unauthorized': 'Unauthorized. Please login again.',
  'session_expired': 'Session expired. Please login again.',

  // Home
  'home': 'Home',
  'welcome': 'Welcome',
  'welcome_back': 'Welcome Back',
  'dashboard': 'Dashboard',

  // Profile
  'profile': 'Profile',
  'my_profile': 'My Profile',
  'settings': 'Settings',
  'notifications': 'Notifications',
  'privacy_policy': 'Privacy Policy',
  'terms_of_service': 'Terms of Service',
  'about': 'About',
  'version': 'Version',
  'language': 'Language',
  'theme': 'Theme',
  'dark_mode': 'Dark Mode',
  'light_mode': 'Light Mode',
};
