const Map<String, String> hiIN = {
  // General
  'app_name': 'परिवर्तन सूत्र',
  'ok': 'ठीक है',
  'cancel': 'रद्द करें',
  'yes': 'हाँ',
  'no': 'नहीं',
  'confirm': 'पुष्टि करें',
  'close': 'बंद करें',
  'back': 'वापस',
  'next': 'अगला',
  'done': 'हो गया',
  'save': 'सहेजें',
  'edit': 'संपादित करें',
  'delete': 'हटाएं',
  'retry': 'पुनः प्रयास करें',
  'loading': 'लोड हो रहा है...',
  'please_wait': 'कृपया प्रतीक्षा करें...',
  'success': 'सफलता',
  'error': 'त्रुटि',
  'warning': 'चेतावनी',
  'info': 'जानकारी',
  'search': 'खोजें',
  'no_data': 'कोई डेटा नहीं मिला',
  'something_went_wrong': 'कुछ गलत हो गया',
  'try_again': 'पुनः प्रयास करें',

  // Auth
  'login': 'लॉगिन',
  'logout': 'लॉगआउट',
  'register': 'पंजीकरण',
  'sign_in': 'साइन इन',
  'sign_up': 'साइन अप',
  'sign_out': 'साइन आउट',
  'forgot_password': 'पासवर्ड भूल गए?',
  'reset_password': 'पासवर्ड रीसेट करें',
  'change_password': 'पासवर्ड बदलें',
  'email': 'ईमेल',
  'password': 'पासवर्ड',
  'confirm_password': 'पासवर्ड की पुष्टि करें',
  'full_name': 'पूरा नाम',
  'phone_number': 'फ़ोन नंबर',
  'otp': 'ओटीपी',
  'enter_otp': 'ओटीपी दर्ज करें',
  'resend_otp': 'ओटीपी पुनः भेजें',
  'verify': 'सत्यापित करें',
  'verification': 'सत्यापन',

  // Validation
  'field_required': 'यह फ़ील्ड आवश्यक है',
  'invalid_email': 'कृपया एक वैध ईमेल पता दर्ज करें',
  'invalid_phone': 'कृपया एक वैध 10-अंकीय फ़ोन नंबर दर्ज करें',
  'password_too_short': 'पासवर्ड कम से कम 8 अक्षर का होना चाहिए',
  'password_too_long': 'पासवर्ड 32 अक्षरों से अधिक नहीं होना चाहिए',
  'password_no_uppercase': 'पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए',
  'password_no_lowercase': 'पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए',
  'password_no_digit': 'पासवर्ड में कम से कम एक अंक होना चाहिए',
  'password_no_special': 'पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए',
  'passwords_not_match': 'पासवर्ड मेल नहीं खाते',
  'invalid_otp': 'कृपया एक वैध 6-अंकीय ओटीपी दर्ज करें',
  'name_too_short': 'नाम कम से कम 2 अक्षर का होना चाहिए',
  'name_too_long': 'नाम 50 अक्षरों से अधिक नहीं होना चाहिए',

  // Network
  'no_internet': 'इंटरनेट कनेक्शन नहीं है',
  'network_error': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
  'timeout_error': 'अनुरोध का समय समाप्त हो गया। कृपया पुनः प्रयास करें।',
  'server_error': 'सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।',
  'unauthorized': 'अनधिकृत। कृपया पुनः लॉगिन करें।',
  'session_expired': 'सत्र समाप्त हो गया। कृपया पुनः लॉगिन करें।',

  // Home
  'home': 'होम',
  'welcome': 'स्वागत है',
  'welcome_back': 'वापसी पर स्वागत है',
  'dashboard': 'डैशबोर्ड',

  // Profile
  'profile': 'प्रोफ़ाइल',
  'my_profile': 'मेरी प्रोफ़ाइल',
  'settings': 'सेटिंग्स',
  'notifications': 'सूचनाएं',
  'privacy_policy': 'गोपनीयता नीति',
  'terms_of_service': 'सेवा की शर्तें',
  'about': 'के बारे में',
  'version': 'संस्करण',
  'language': 'भाषा',
  'theme': 'थीम',
  'dark_mode': 'डार्क मोड',
  'light_mode': 'लाइट मोड',
};
